services:
  - type: web
    name: pattern-quest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
